### ISSUE TITLE
Eastern Townhall Document translation of Fund 8 Proposals,Challenge Setting and Challenges

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#122]
The pages [Eastern Townhall Fund 8 Proposals](<>) & [Eastern Townhall Fund 8 Challenge Settings](<>) & [Eastern Townhall Fund 8 Challenges](<>) are up and need to be translated. This epic is here to track the issues of the Eastern Townhall proposals, challenge setting and challenges for fund 8.

### Fund 8 Proposal Translation
- [x] Set up Translate Epic
- [ ] Translate Fund 8 Proposals

### Fund 8 Challenges Translation
- [ ] Translate Fund 8 Challenges.
  - [x] #123 
  - [x] #124 
  - [x] #125 
  - [x] #126
  - [x] #128 
  - [x] #129
  - [x] #127
  - [ ] #130
  - [x] #131
  - [x] #132
  - [x] #133
  - [x] #134
  - [x] #135
  - [x] #136
  - [x] #137
  - [x] #138
  - [x] #139
  - [ ] #140
  - [x] #141
  - [x] #142
  - [x] #143
  - [x] #144

Translations can be done by anyone in the community; Language moderators need to approve the changes and submit the pull requests.

Please refer to the [Contributors Guide](/README/en/CONTRIBUTING.md) to understand what it means to contribute.

**Language moderators (assignees)**: Please check the issues with the respective category(s) above when you have completed and approved the translations for each of the issues and a pull request has been submitted. That way others know it has been done. 

**Site Maintainers/Admins:** Check the pull requests and merge the files. Please check off the languages merged above so we know what is left to do.

*NOTE*: Fixes are typically required because the translation software (GitLocalize) incorrectly escapes special characters used in Hugo markdown files.
