### ISSUE TITLE
[Infrastructure]: Github action for testing site builds on active pull requests

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#174]
## Github Action bot: PR Test Commentor
Create a Github action that tests individual units of the building process of the site and auto post a comment of the results on every open pull requests. This is to make sure that when people make changes maintainers can see wether or not the site still comples and makes contributing faster.

#### Tasks:
- [x] Test Bot with a test repository.
- [x]  Build an output for the site buid to test wether it suceeds or fails
- [x] Build a dependency output to test wether depencies suceed or fail
- [x] Create a log for analysing errors that may occur if the site does not build
