### ISSUE TITLE
Eastern Townhall Document translation of  Fund 7 Proposals,Challenge Setting and Challenges

### ISSUE THREAD

**Issue by PardusEidolon** [C3ETH/c3eth.github.io#48]
The pages [Eastern Townhall Fund 7 Proposals](<https://easterntownhall.com/catalyst/fund7/>) & [Eastern Townhall Fund 7 Challenge Settings](<https://easterntownhall.com/catalyst/fund7/challenge-setting-proposals/>) & [Eastern Townhall Fund 7 Challenges](<https://easterntownhall.com/catalyst/fund7/challenges/>) are up and need to be translated. This epic is here to track the issues of the Eastern Townhall proposals, challenge setting and challenges for fund 7.

### Fund 7 Proposal Translation
- [x] Set up Translate Epic
- [ ] Translate Fund 7 Proposals

### Fund 7 Challenge Setting Translation
- [ ] Translate Fund 7 Challenge setting.
   - [ ]  #73 

### Fund 7 Challenges Translation
- [ ] Translate Fund 7 Challenges.
   - [ ] #49 
   - [ ] #50 
   - [ ] #51
   - [ ] #52
   - [ ] #53
   - [x] #54 
   - [x] #55 
   - [x] #56
   - [x] #57 
   - [x] #58
   - [x] #59
   - [x] #60 
   - [x] #61 
   - [x] #62 
   - [x] #63 
   - [ ] #64 
   - [x] #65 
   - [x] #66 
   - [x] #67 
   - [x] #68 
   - [x] #69 
   - [x] #70 
   - [x] #71 
   - [x] #72 

Translations can be done by anyone in the community; Language moderators need to approve the changes and submit the pull requests.

Please refer to the [Contributors Guide](/README/en/CONTRIBUTING.md) to understand what it means to contribute.

**Language moderators (assignees)**: Please check the issues with the respective category(s) above when you have completed and approved the translations for each of the issues and a pull request has been submitted. That way others know it has been done. 

**Site Maintainers/Admins:** Check the pull requests and merge the files. Please check off the languages merged above so we know what is left to do.

*NOTE*: Fixes are typically required because the translation software (GitLocalize) incorrectly escapes special characters used in Hugo markdown files.
